// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mgdawiobklcmghpeybsi.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1nZGF3aW9ia2xjbWdocGV5YnNpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTgxOTk5NjEsImV4cCI6MjA3Mzc3NTk2MX0.UrArCLhL2bqKRjeQSyNOEsOmnfIAK2H0RShS1mZT_jw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});